// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type ProductPackSize struct {
	ID          uuid.UUID `json:"id"`
	ProductLine string    `json:"product_line"`
	PackSize    int64     `json:"pack_size"`
	UpdatedAt   time.Time `json:"updated_at"`
	CreatedAt   time.Time `json:"created_at"`
}
