// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: pack_size.sql

package db

import (
	"context"
)

const createPackSize = `-- name: CreatePackSize :one
INSERT INTO product_pack_sizes (
  product_line,
  pack_size
) VALUES (
  $1, $2
) RETURNING id, product_line, pack_size, updated_at, created_at
`

type CreatePackSizeParams struct {
	ProductLine string `json:"product_line"`
	PackSize    int64  `json:"pack_size"`
}

func (q *Queries) CreatePackSize(ctx context.Context, arg CreatePackSizeParams) (ProductPackSize, error) {
	row := q.db.QueryRowContext(ctx, createPackSize, arg.ProductLine, arg.PackSize)
	var i ProductPackSize
	err := row.Scan(
		&i.ID,
		&i.ProductLine,
		&i.PackSize,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
