// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePackSize(ctx context.Context, arg CreatePackSizeParams) (ProductPackSize, error)
	DeletePackSize(ctx context.Context, id uuid.UUID) error
	GetPackSize(ctx context.Context, id uuid.UUID) (ProductPackSize, error)
	ListPackSizesByProductLine(ctx context.Context, productLine string) ([]ProductPackSize, error)
	ListProductLines(ctx context.Context) ([]string, error)
	UpdatePackSizes(ctx context.Context, arg UpdatePackSizesParams) (ProductPackSize, error)
}

var _ Querier = (*Queries)(nil)
