// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreatePackSize(ctx context.Context, arg CreatePackSizeParams) (ProductPackSize, error)
}

var _ Querier = (*Queries)(nil)
